### ISSUE TITLE
visualization issue

### ISSUE THREAD

**Issue by wangxiao5791509** [fzh0917/STMTrack#1]
Hi, thanks for sharing your code. I find a bug on visualization: [line 361](https://github.com/fzh0917/STMTrack/blob/1df153820f2075ac4c3f6dfd9b127514b3d92d56/videoanalyst/pipeline/tracker_impl/stmtrack_tracker.py#L361) and [line 370](https://github.com/fzh0917/STMTrack/blob/1df153820f2075ac4c3f6dfd9b127514b3d92d56/videoanalyst/pipeline/tracker_impl/stmtrack_tracker.py#L370).  'frame_idx' -> 'cur_frame_idx'. 

        if self._hp_visualization:
            score1 = tensor_to_numpy(score[0])[:, 0]
            vsm.visualize(score1, self._hp_score_size, im_q_crop, self._state['cur_frame_idx'], 'raw_score')

**Comment by fzh0917** [comment]
Thanks for pointing out this issue. We have fixed it in the latest commit.
