### ISSUE TITLE
memory size problem

### ISSUE THREAD

**Issue by DavidZhangdw** [fzh0917/STMTrack#10]
Hi, authors, How to change the memory size during inference?

**Comment by fzh0917** [comment]
> Hi, authors, How to change the memory size during inference?

Set the hyper-parameter [`num_segments` (I am clickable)](https://github.com/fzh0917/STMTrack/blob/61730c19ec0eaea393fa3119b8d71023e1173d5b/videoanalyst/pipeline/tracker_impl/stmtrack_tracker.py#L43) in your inference config files.

**Comment by fzh0917** [comment]
This issue is closed. Feel free to create new issues if you have any questions.
