### ISSUE TITLE
A typo in your papper

### ISSUE THREAD

**Issue by zzg-zzg** [fzh0917/STMTrack#11]
Thank you for your excellent work.
I read your paper and found an obvious typo.
In the last paragraph of section 3.3 ，STM's citation number should be [37] and GraghMemVOS should be [30].
Another question I want to know is whether dividing the features extracted by keys and values will affect the detection of occluded objects. What should I do if I want the bbox to contain the occluded part？

**Comment by fzh0917** [comment]
@zzg-zzg Thank you for your kind reminder. 

Q: whether dividing the features extracted by keys and values will affect the detection of occluded objects?
A: no. 

Q: What should I do if I want the bbox to contain the occluded part？
A: Frankly speaking, it's not easy to get the bounding boxes that contain the occluded parts. A straightforward solution is to using the historical target information, especially the one in the previous frame.

**Comment by fzh0917** [comment]
This issue is closed. Feel free to create new issues if you have any questions.
