### ISSUE TITLE
issue about the hyperparameters？

### ISSUE THREAD

**Issue by axiaomu** [fzh0917/STMTrack#12]
Hello, thank you for your code. During the test, can you tell me how to get the best parameters: test_lr、  window_influence、 penalty_k.  Thanks.

**Comment by xiaoxianya** [comment]
同样的疑问,为什么超参可以调到小数点后几十位

**Comment by fzh0917** [comment]
> Hello, thank you for your code. During the test, can you tell me how to get the best parameters: test_lr、 window_influence、 penalty_k. Thanks.

@axiaomu Sorry for the late reply. The "best" hyper-parameters are obtained by a hyper-parameter searching program, see [this](https://github.com/MegviiDetection/video_analyst/blob/master/main/hpo.py) and [this](https://github.com/STVIR/pysot/blob/master/tools/hp_search.py) for more details. @xiaoxianya
