### ISSUE TITLE
Hi, can I add your wechat to have a deeper talk on this work? 

### ISSUE THREAD

**Issue by wangxiao5791509** [fzh0917/STMTrack#13]
Hi, can I add your WeChat to have a deeper talk on this work? Currently, I am extending this tracker into dual-modality version. My wechat is **wangxiao5791509**. Thanks.

**Comment by fzh0917** [comment]
> Hi, can I add your WeChat to have a deeper talk on this work? Currently, I am extending this tracker into dual-modality version. My wechat is **wangxiao5791509**. Thanks.

Thanks for being interested in this work. I have contacted you privately.
