### ISSUE TITLE
About receptive field

### ISSUE THREAD

**Issue by zzg-zzg** [fzh0917/STMTrack#16]
Thanks for your work again.
I encountered a problem while using your network . 
The feature map output by your network neck is 17*17, so six 3*3 convolutional layers can still meet the requirements of the receptive field. 
If the size of the input picture increases and the feature map increases, and the tracking target itself is relatively large, can it be possible to expand the receptive field by stacking 3*3 convolutional layers? Or is there any better solution?

**Comment by fzh0917** [comment]
@zzg-zzg  Sorry, I can't figure out your question well. Do you mean that, how to increase the receptive field of the backbones?

**Comment by zzg-zzg** [comment]
I mean the feature map output from memory reader will be fed into the regression head. There are six 3*3convs in the regression head, so each anchor point should theoretically have a receptive field of 13*13, right?

**Comment by fzh0917** [comment]
Yes. You are right, but I think that you should also calculate the receptive field of the backbones.

**Comment by fzh0917** [comment]
This issue is closed. Feel free to reopen this or create new issues if you have any questions.
