### ISSUE TITLE
About continuing training with your trained model

### ISSUE THREAD

**Issue by 972821054** [fzh0917/STMTrack#24]
Hi, your article is excellent! I benefited a lot from watching it! I have a question to ask you. I want to continue training on the basis of your training. Is it correct to modify the yaml file as follows?
![image](https://user-images.githubusercontent.com/83146207/218252023-8f056a2d-b7cc-4474-bc0b-05eb3a6d4150.png)
![image](https://user-images.githubusercontent.com/83146207/218252034-c04b8041-6cc5-4089-9fae-2633c0057c85.png)
I would be very grateful if you get back to me!

**Comment by fzh0917** [comment]
> Hi, your article is excellent! I benefited a lot from watching it! I have a question to ask you. I want to continue training on the basis of your training. Is it correct to modify the yaml file as follows? ![image](https://user-images.githubusercontent.com/83146207/218252023-8f056a2d-b7cc-4474-bc0b-05eb3a6d4150.png) ![image](https://user-images.githubusercontent.com/83146207/218252034-c04b8041-6cc5-4089-9fae-2633c0057c85.png) I would be very grateful if you get back to me!

Yes, you are right.
