### ISSUE TITLE
About selecting a model

### ISSUE THREAD

**Issue by 972821054** [fzh0917/STMTrack#25]
Hello, how did you choose a model? And how do you set it up when optimizing your training strategy?

**Comment by 972821054** [comment]
By comparing different models, I found that this method does not say to distinguish between excellent models and bad models. For example, my 38th epoch is better than 39 epochs. How can I choose the best model from many models? that?

**Comment by fzh0917** [comment]
> Hello, how did you choose a model? And how do you set it up when optimizing your training strategy?

What's the meaning of choosing a model?
The model optimization strategy is a general topic, you can find a lot of ideas and inspirations from many web blogs and forums.

**Comment by fzh0917** [comment]
> 

You can test your training model on a validation dataset after each epoch by setting an evaluation metric. The model that achieves the maximum score or the minimum error is the best.

**Comment by fzh0917** [comment]
> By comparing different models, I found that this method does not say to distinguish between excellent models and bad models. For example, my 38th epoch is better than 39 epochs. How can I choose the best model from many models? that?

You can test your training model on a validation dataset after each epoch by setting an evaluation metric. The model that achieves the maximum score or the minimum error is the best.

**Comment by 972821054** [comment]
@fzh0917Hello, thank you for your reply. I did not describe my problem clearly. I want to know whether there is a progressive relationship between each epoch, or every time a new epoch is trained, the parameters will be initialized, and Do not use parameters from the previous epoch

**Comment by fzh0917** [comment]
> @fzh0917Hello, thank you for your reply. I did not describe my problem clearly. I want to know whether there is a progressive relationship between each epoch, or every time a new epoch is trained, the parameters will be initialized, and Do not use parameters from the previous epoch

First, there is no progressive relationship between each epoch, especially after the model converges.
Second, the network parameters are only initialized before the first epoch begins. I mean, the network parameter values between the 2nd and the Nth epoch are from the previous epochs.

**Comment by 972821054** [comment]
@fzh0917 Thank you very much for your reply, I've basically cleared it up and I'll close this question.
