### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by 972821054** [fzh0917/STMTrack#26]
Hello, thank you for your contribution in the VOT field and for sharing such high-quality code.
I have a question I would like to ask you. When I was reading the source code, I was not very clear about the functions in the figure below in the model. I found that there is basically this code in each of them. What is its function? Is it a parameter to initialize the model? If yes, what should I do if I want to use a previously trained model?
Thank you in advance!
![image](https://user-images.githubusercontent.com/83146207/221535162-8827a0a3-b7e4-42f6-a360-b5769f358e53.png)

**Comment by fzh0917** [comment]
@972821054 Yes, every module has an `update_params` method. Its function is similar to the built-in method `__init__` of an object. This is to say, it's usually used to create network architecture and initialize learnable parameters. The pre-trained model weights you provided will be loaded after the execution of `update_params` function of all network modules.
By the way,  the design philosophy of this framework determines that we cannot directly create network architecture and initialize learnable parameters in the constructor method `__init__` . Therefore, we need to use an additional function to do these things.

**Comment by 972821054** [comment]
@fzh0917 
thank you for your reply!
If I don't set the update_params function, what kind of problems will the network training produce? Such as parameters in the model?

**Comment by fzh0917** [comment]
> @fzh0917 thank you for your reply! If I don't set the update_params function, what kind of problems will the network training produce? Such as parameters in the model?

Every registered module inherits a base class. Thus, it has an inherited method `update_params`. So, if you don't set the `update_params` method explicitly, the default one would be executed.

**Comment by 972821054** [comment]
@fzh0917 Thank you very much for your reply, I've basically cleared it up and I'll close this question.
