### ISSUE TITLE
 About learning rate

### ISSUE THREAD

**Issue by 972821054** [fzh0917/STMTrack#27]
May I ask why you set the learning rate in the yaml in fulldata to 0.02, will there be any problems with this learning rate?
![image](https://user-images.githubusercontent.com/83146207/223040616-6964372d-2c5f-4d5c-957d-c709dc4b052d.png)

**Comment by fzh0917** [comment]
> May I ask why you set the learning rate in the yaml in fulldata to 0.02, will there be any problems with this learning rate? ![image](https://user-images.githubusercontent.com/83146207/223040616-6964372d-2c5f-4d5c-957d-c709dc4b052d.png)

Because the average bounding boxes and image qualities of `fulldata` is lower than `GOT-10k`, only when the optimizer uses a larger iteration step size can the model converge quickly.

**Comment by 972821054** [comment]
@ thanks！
