### ISSUE TITLE
KeyError: 'Non-existent config key: train.track.data.transformer.RandomCropTransformer.x_size'

### ISSUE THREAD

**Issue by n1-k0** [fzh0917/STMTrack#4]
作者你好，我跑了您的代码，发现一些代码中缺少了x_size这一个参数（比如RandomCropTransformer这个类下面的default_hyper_params，DenseboxTarget这个类下同样缺失），导致在train函数中root_cfg.merge_from_file(exp_cfg_path)出现错误，请问这些地方的x_size应该设为多少？

**Comment by fzh0917** [comment]
fixed.
