### ISSUE TITLE
What does the Foreground Label Map mean? 

### ISSUE THREAD

**Issue by longmalongma** [fzh0917/STMTrack#5]
Hi, thanks for your good wokr. What does the Foreground Label Map mean? How to achieve it?

**Comment by fzh0917** [comment]
> Hi, thanks for your good wokr. What does the Foreground Label Map mean? How to achieve it?

The foreground-background label map indicates the locations of foregrounds and backgrounds.
In training phase, we can achieve it using the corresponding ground truth.
In inference phase, we can get it using the predicted target bounding box by our tracker.

**Comment by fzh0917** [comment]
This issue is closed. Feel free to create new issues if you have any questions.
