### ISSUE TITLE
Issues about the json files of UAV123 datasets 

### ISSUE THREAD

**Issue by 20713** [fzh0917/STMTrack#6]
Dear author, Should I put the JSON file of the UAV dataset in the same level directory of the uav123 python file? And, where is the  the  json  files of UAV123 datasets .Could you share it? Thanks a lot!

**Comment by fzh0917** [comment]
> Dear author, Should I put the JSON file of the UAV dataset in the same level directory of the uav123 python file? And, where is the the json files of UAV123 datasets .Could you share it? Thanks a lot!

Hello, my friend, what's the JSON file? Here is the directory information of my used UAV123 dataset. I believe that It's easy to download it from the official website for you. 
![image](https://user-images.githubusercontent.com/23057107/128362478-634859f2-08ed-495e-a233-19715e39b9e8.png)
Good luck!

**Comment by 20713** [comment]
Thanks for your reply! As you said ，it is easy to download the uav123 datasets .But .When i test your model with UAV123 dataset .I run the "python test.py --config /home/yingjy/STMTrack-main/experiments/stmtrack/test/UAV123/stmtrack-googlenet-uav123.yaml" command .An error happened ,it remined me that there is no uav123.json file. In your code,i found where is the uav123.json file appears.&nbsp;As shown in the figure&nbsp; below：



And how i test your model with the UAV123 dataset? Thanks a lot!












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzh0917/STMTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 晚上9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzh0917/STMTrack] Issues about the json files of UAV123 datasets  (#6)





  
Dear author, Should I put the JSON file of the UAV dataset in the same level directory of the uav123 python file? And, where is the the json files of UAV123 datasets .Could you share it? Thanks a lot!
  
Hello, my friend, what's the JSON file? Here is the directory information of my used UAV123 dataset. I believe that It's easy to download it from the official website for you.
 
 Good luck!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fzh0917** [comment]
It seems something went wrong. I can't see your figure. Besides, it will be very convenient for us if you could paste the error log here.

**Comment by 20713** [comment]
Thanks for your reply! Did you mean that you can't see the pictures that i sent you? OK,i recorded the error log and screenshot as follows.
screenshot:

error logs:


"Traceback (most recent call last):
&nbsp; File "test.py", line 72, in <module&gt;
&nbsp; &nbsp; tester.test()
&nbsp; File "/home/yingjy/STMTrack-main/videoanalyst/engine/tester/tester_impl/uav123.py", line 64, in test
&nbsp; &nbsp; report_dir=report_dir)
&nbsp; File "/home/yingjy/STMTrack-main/videoanalyst/evaluation/got_benchmark/experiments/uav123.py", line 27, in __init__
&nbsp; &nbsp; self.dataset = UAV123(root_dir, version)
&nbsp; File "/home/yingjy/STMTrack-main/videoanalyst/evaluation/got_benchmark/datasets/uav123.py", line 29, in __init__
&nbsp; &nbsp; self._check_integrity(root_dir, version)
&nbsp; File "/home/yingjy/STMTrack-main/videoanalyst/evaluation/got_benchmark/datasets/uav123.py", line 83, in _check_integrity
&nbsp; &nbsp; with open(meta_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yingjy/STMTrack-main/videoanalyst/evaluation/got_benchmark/datasets/uav123.json'&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "


So, could you give me some resolutions about how to test your model with uav123 datasets?
I'm very interested in your method.&nbsp;&nbsp;I hope I can get your advice.&nbsp;Looking&nbsp; forward to your reply.
Wishing you a happy life.











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzh0917/STMTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月6日(星期五) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fzh0917/STMTrack] Issues about the json files of UAV123 datasets  (#6)





 
It seems something went wrong. I can't see your figure. Besides, it will be very convenient for us if you could paste the error log here.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fzh0917** [comment]
You are right. There is indeed a `uav123.json` file. It's my mistake. I submitted my local PC's project to here, instead of the remote server's one. Actually, This repository is built on top of the SOT codebase [video_analyst](https://github.com/MegviiDetection/video_analyst), so you can download the `uav123.json` file as well as the `lasot.json` file from here: [https://github.com/MegviiDetection/video_analyst/tree/master/videoanalyst/evaluation/got_benchmark/datasets](https://github.com/MegviiDetection/video_analyst/tree/master/videoanalyst/evaluation/got_benchmark/datasets).

**Comment by fzh0917** [comment]
This issue is closed. Feel free to create new issues if you have any questions.
