### ISSUE TITLE
issue about the dataset of GOT-10k

### ISSUE THREAD

**Issue by Zexuanxexuan** [fzh0917/STMTrack#7]
Dear Author,I have read your paper carefully, but I am a beginner of visual tracking area. I want to test the pre-trained model. But when I run the command 

> python main/test.py --config experiments/stmtrack/test/got10k/stmtrack-googlenet-got.yaml 

I  meet 

> Exception: Dataset /STMTrack/datasets/GOT-10k/test/list.txt not found or corrupted. 

But I have download the got-10k dataset of your link 
https://drive.google.com/file/d/17wQ9lvEa4jLhv72TZatw03EHUx9UgTcA/view?usp=sharing
and then it come many files when I unzip it
![image](https://user-images.githubusercontent.com/42834825/128493609-a61a85a0-2b4b-4e1c-85a0-0e43354cd946.png)
How can I solve this problem?Thanks

**Comment by fzh0917** [comment]
> Dear Author,I have read your paper carefully, but I am a beginner of visual tracking area. I want to test the pre-trained model. But when I run the command
> 
> > python main/test.py --config experiments/stmtrack/test/got10k/stmtrack-googlenet-got.yaml
> 
> I meet
> 
> > Exception: Dataset /STMTrack/datasets/GOT-10k/test/list.txt not found or corrupted.
> 
> But I have download the got-10k dataset of your link
> https://drive.google.com/file/d/17wQ9lvEa4jLhv72TZatw03EHUx9UgTcA/view?usp=sharing
> and then it come many files when I unzip it
> ![image](https://user-images.githubusercontent.com/42834825/128493609-a61a85a0-2b4b-4e1c-85a0-0e43354cd946.png)
> How can I solve this problem?Thanks

The google drive link I shared is the GOT-10k test results. If you want to test the model, you can download the GOT-10k dataset from the official website: [http://got-10k.aitestunion.com/downloads](http://got-10k.aitestunion.com/downloads). The dataset provides all of you need.

Good luck!

**Comment by Zexuanxexuan** [comment]
> > Dear Author,I have read your paper carefully, but I am a beginner of visual tracking area. I want to test the pre-trained model. But when I run the command
> > > python main/test.py --config experiments/stmtrack/test/got10k/stmtrack-googlenet-got.yaml
> > 
> > 
> > I meet
> > > Exception: Dataset /STMTrack/datasets/GOT-10k/test/list.txt not found or corrupted.
> > 
> > 
> > But I have download the got-10k dataset of your link
> > https://drive.google.com/file/d/17wQ9lvEa4jLhv72TZatw03EHUx9UgTcA/view?usp=sharing
> > and then it come many files when I unzip it
> > ![image](https://user-images.githubusercontent.com/42834825/128493609-a61a85a0-2b4b-4e1c-85a0-0e43354cd946.png)
> > How can I solve this problem?Thanks
> 
> The google drive link I shared is the GOT-10k test results. If you want to test the model, you can download the GOT-10k dataset from the official website: http://got-10k.aitestunion.com/downloads. The dataset provides all of you need.
> 
> Good luck!

Thank you very much！！

**Comment by fzh0917** [comment]
This issue is closed. Feel free to create new issues if you have any questions.
