### ISSUE TITLE
Issue about got-10k Training

### ISSUE THREAD

**Issue by DavidZhangdw** [fzh0917/STMTrack#8]
Hi, author. Thanks for your nice work. I excute offline training for the got10k benchmark. To be specific, I set the number of samples per epoch to 150,000 and the mini-batch size to 15, other settings are same with your code.  The whole training phase takes about 1.5 days with one NVIDIA Tesla V100 GPU. But, the evaluation looks bad, Do you meets this problem? or do you have some suggestions. 
![1628252602](https://user-images.githubusercontent.com/35833888/128509968-ccaaa52c-a72c-4873-b4f9-90c3dd7b76fb.jpg)

**Comment by fzh0917** [comment]
@DavidZhangdw Your batch is a bit small. Try to set it to 32. As your figure shown (see the `iou` metric), your trained model did not converge.
Good luck!

**Comment by DavidZhangdw** [comment]
If train on got-10k only, what is the final convergent iou?

**Comment by fzh0917** [comment]
> If train on got-10k only, what is the final convergent iou?

About 0.85~

**Comment by DavidZhangdw** [comment]
Thanks, How to change the memory size during inference?

**Comment by 972821054** [comment]
@fzh0917 @DavidZhangdw 
Hello, after I trained on my own data set, the iou indicator did not converge. Did you solve this problem?
