### ISSUE TITLE
what does score_offset means?

### ISSUE THREAD

**Issue by Idontunderstand-kjl** [fzh0917/STMTrack#9]
![image](https://user-images.githubusercontent.com/60867922/129443201-62409511-6c76-49b8-b6c9-a0e0c4ffc351.jpeg)
as what the picture above show,why score_offset equals that

**Comment by fzh0917** [comment]
@Idontunderstand-kjl As shown in the following figure, the green square represents the original image, the yellow square represents the the range that can be represented by the score map. So, the equation to compute the offsets is it.

![image](https://user-images.githubusercontent.com/23057107/129445956-28945901-e48b-4cd6-87e6-7f0ed2fe963d.png)

**Comment by Idontunderstand-kjl** [comment]
sincerely thanks for your explaination!but why

**Comment by Idontunderstand-kjl** [comment]
sincerely thanks for your explaination!but why both q_size and score_size have to subtract 1 ?Maybe it is about odd and even?

**Comment by Idontunderstand-kjl** [comment]
hi

**Comment by fzh0917** [comment]
> sincerely thanks for your explaination!but why both q_size and score_size have to subtract 1 ?Maybe it is about odd and even?

Yes.

**Comment by fzh0917** [comment]
This issue is closed. Feel free to create new issues if you have any questions.
